import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { build } from 'esbuild';
import { ajv, standaloneReferences } from './src/validation-compiler.js';
import { contentSchema, legendaryExpansionSchema } from './src/content-schema.js';

// Run in Node at development/build time. Browsers only execute the generated functions.
ajv.addSchema({ ...contentSchema, $id: 'urn:frontier:compiled:content' });
ajv.addSchema({ ...legendaryExpansionSchema, $id: 'urn:frontier:compiled:legendary-expansion' });
const generated = standaloneCode(ajv, { ...standaloneReferences, validateContentStructure: 'urn:frontier:compiled:content', validateLegendaryExpansionStructure: 'urn:frontier:compiled:legendary-expansion' });
// Bundle Ajv's small static Unicode/equality helpers so the ESM output has no runtime require.
const result = await build({ stdin: { contents: generated, resolveDir: resolve('.') }, bundle: true, format: 'esm', platform: 'browser', minify: true, write: false });
const output = '// Generated by packages/shared/generate-validators.ts. Do not edit.\n' + result.outputFiles[0]!.text;
if (/\bnew Function\s*\(|\beval\s*\(/.test(output)) throw new Error('DYNAMIC_CODE_IN_VALIDATORS');
await writeFile(new URL('./src/validators.generated.js', import.meta.url), output);
const declarations = "// Generated validator interfaces; implementation is static JavaScript.\nimport type { ValidateFunction } from 'ajv';\n" + Object.keys({ ...standaloneReferences, validateContentStructure: true, validateLegendaryExpansionStructure: true }).map(name=>`export declare const ${name}: ValidateFunction<unknown>;`).join('\n') + '\n';
await writeFile(new URL('./src/validators.generated.d.ts', import.meta.url), declarations);
process.stdout.write(`Generated strict CSP-compatible validators (${Buffer.byteLength(output)} bytes).\n`);
