import { useEffect, useRef, useState } from 'react';
import { balance, type ChatStateResponse, type ChatMessage, type CooperationRequest, type PlayerView, type SessionResponse, type TeamPing } from '@frontier/shared';
import type { World } from './World';

export const requestStatusLabel = (status: ChatMessage['status']) => ({ requested: 'Requested', planned: 'Planned', completed: 'Completed', declined: 'Declined', blocked: 'Blocked', expired: 'Expired' }[status ?? 'requested']);
export const pingLabels: Record<TeamPing['category'], string> = { attack: 'Attack here', defend: 'Defend here', resource: 'Resources here', help: 'Help here' };
export const pingSymbols: Record<TeamPing['category'], string> = { attack: '\u2694', defend: '\u25c7', resource: '\u25cf', help: '!' };
export const commanderModeLabel = (mode: 'model' | 'fallback' | undefined) => mode === 'model' ? 'Strategic model active' : 'Strategic model unavailable - rule-based commander active';

export function Communications({ view, session, state, world, close, changed }: { view: PlayerView; session: SessionResponse; state: ChatStateResponse | null; world: World; close: () => void; changed: () => Promise<void> }) {
  const [text, setText] = useState(''), [channel, setChannel] = useState<'all' | 'team'>('team'), [targetAiId, setTargetAiId] = useState('');
  const [resource, setResource] = useState<'food' | 'wood' | 'gold' | 'stone'>('wood'), [amount, setAmount] = useState(100), [pingId, setPingId] = useState(''), [cooperationAi, setCooperationAi] = useState('');
  const [category, setCategory] = useState<TeamPing['category']>('help'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const history = useRef<HTMLDivElement>(null), wasNearEnd = useRef(true);
  const me = view.players.find((player) => player.id === view.playerId), allies = view.players.filter((player) => player.kind === 'ai' && player.teamId === me?.teamId && !player.defeated);
  const pings = (state?.pings ?? []).filter((ping) => ping.expiresTick > view.tick), running = view.status === 'RUNNING';
  const alliedTarget = allies.find((player) => player.id === cooperationAi), resolvedTarget = alliedTarget?.id ?? allies[0]?.id;
  useEffect(() => { if (history.current && wasNearEnd.current) history.current.scrollTop = history.current.scrollHeight; }, [state?.messages.at(-1)?.id]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape') close(); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [close]);
  async function submit(path: string, body: unknown, success?: string) {
    setBusy(true); setError(''); setNotice('');
    try {
      const response = await fetch(path, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(session.csrfToken ? { 'X-CSRF-Token': session.csrfToken } : {}) }, body: JSON.stringify(body) });
      if (!response.ok) { const problem = await response.json() as { code?: string; message?: string }; throw new Error((problem.message ?? problem.code ?? 'Message could not be sent.').replaceAll('_', ' ')); }
      if (path === '/api/chat') setText(''); if (success) setNotice(success); await changed();
    } catch (problem) { setError(problem instanceof Error ? problem.message : 'Communication failed.'); } finally { setBusy(false); }
  }
  const cooperate = (request: CooperationRequest) => void submit('/api/cooperate', request, 'Request sent. Follow its outcome below.');
  const playerName = (id: string) => view.players.find((player) => player.id === id)?.name ?? 'Commander';
  const sendPing = () => void submit('/api/ping', { category, xMm: Math.max(0, Math.min(view.map.widthMm - 1, Math.round(world.camera.target.x * 1000))), zMm: Math.max(0, Math.min(view.map.heightMm - 1, Math.round(world.camera.target.z * 1000))) }, 'Team signal sent at your camera center.');
  return <section className="communications-panel" data-gameplay-hotkeys="suspend" role="dialog" aria-label="Chat and team signals"><header><div><span className="eyebrow">KEEP YOUR COMPANY CLOSE</span><h2>Dispatches</h2></div><button className="quiet-button" aria-label="Close chat and team signals" onClick={close}>Close</button></header>
    <p className="small-copy">Alliances remain fixed. A request becomes completed only after the host confirms its outcome.</p>
    {!!view.players.some((player) => player.kind === 'ai') && <details className="commander-statuses"><summary>Commander control modes</summary>{view.players.filter((player) => player.kind === 'ai').map((player) => <div key={player.id}><b>{player.name}</b><small>{commanderModeLabel(player.aiMode)}</small></div>)}</details>}
    {state && <p className="chat-privacy">{state.sendHumanChat ? 'Authorized human chat may be included in model observations.' : 'Human chat stays with players. Free-form text is not sent to the model; use presets to request AI cooperation.'}</p>}
    {error && <p className="recovery-error" role="alert">{error}</p>}{notice && <p className="recovery-notice" role="status">{notice}</p>}
    <div className="chat-history" role="log" aria-label="Recent messages" aria-live="polite" ref={history} onScroll={() => { if (history.current) wasNearEnd.current = history.current.scrollHeight - history.current.scrollTop - history.current.clientHeight < 40; }}>
      {(state?.messages ?? []).map((message) => <article key={message.id} className={`chat-message chat-${message.source}`} data-request-id={message.requestId}><div><b>{playerName(message.senderId)}</b><span>{message.source === 'model' ? 'Model reply' : message.source === 'system' ? 'System outcome' : message.channel === 'team' ? 'Team' : 'Everyone'} · {Math.floor(message.tick / balance.rules.simulationHz / 60)}:{String(Math.floor(message.tick / balance.rules.simulationHz) % 60).padStart(2, '0')}</span></div>{message.targetAiId && <small>To {playerName(message.targetAiId)}</small>}<p>{message.text}</p>{message.status && <span className={`request-status request-${message.status}`}>{requestStatusLabel(message.status)}</span>}{message.requestId && <small className="request-reference" title={message.requestId}>Request {message.requestId.slice(-8)}</small>}</article>)}
      {state && !state.messages.length && <p className="chat-empty">Your company's dispatches will appear here.</p>}
      {!state && <p className="chat-empty">Receiving your authorized messages...</p>}
    </div>
    <form className="chat-compose" onSubmit={(event) => { event.preventDefault(); if (text.trim()) void submit('/api/chat', { text: text.trim(), channel, ...(targetAiId && channel === 'team' ? { targetAiId } : {}) }); }}><div className="chat-recipient"><label>AUDIENCE<select aria-label="Chat audience" value={channel} onChange={(event) => { setChannel(event.target.value as 'all' | 'team'); if (event.target.value === 'all') setTargetAiId(''); }} disabled={busy}><option value="team">Teammates</option><option value="all">Everyone</option></select></label><label>ADDRESS A COMMANDER<select aria-label="Address allied AI" value={targetAiId} onChange={(event) => setTargetAiId(event.target.value)} disabled={busy || channel !== 'team'}><option value="">Team conversation</option>{allies.map((player) => <option key={player.id} value={player.id}>{player.name}</option>)}</select></label></div><label className="chat-message-label">MESSAGE<textarea aria-label="Chat message" maxLength={500} rows={2} value={text} onChange={(event) => setText(event.target.value)} placeholder="Coordinate with your company..." disabled={busy || view.status === 'LOADING' || view.status === 'COUNTDOWN'} /></label><div className="chat-send-row"><small>{text.length}/500 · Plain text</small><button className="quiet-button" disabled={busy || !text.trim() || view.status === 'LOADING' || view.status === 'COUNTDOWN'}>Send message</button></div></form>
    <details className="cooperation-section"><summary>Preset cooperation</summary>{resolvedTarget ? <><label>ALLIED COMMANDER<select aria-label="Cooperation commander" value={resolvedTarget} onChange={(event) => setCooperationAi(event.target.value)} disabled={busy}>{allies.map((player) => <option value={player.id} key={player.id}>{player.name}</option>)}</select></label><p className="small-copy">Presets remain available when forwarding human chat to the model is disabled. The commander may accept, decline, or become blocked by ordinary resources and vision.</p><button className="quiet-button" disabled={busy || !running} onClick={() => cooperate({ targetAiId: resolvedTarget, action: 'defend_base' })}>Request base defense</button><div className="cooperation-tribute"><label>RESOURCE<select aria-label="Requested tribute resource" value={resource} onChange={(event) => setResource(event.target.value as typeof resource)}>{balance.resourceOrder.map((id) => <option key={id}>{id}</option>)}</select></label><label>AMOUNT<input aria-label="Requested tribute amount" type="number" min={1} max={1000} value={amount} onChange={(event) => setAmount(Number(event.target.value))} /></label><button className="quiet-button" disabled={busy || !running || !Number.isInteger(amount) || amount < 1 || amount > 1000} onClick={() => cooperate({ targetAiId: resolvedTarget, action: 'tribute', resource, amount })}>Request tribute</button></div><div className="cooperation-attack"><label>TEAM SIGNAL<select aria-label="Attack request signal" value={pingId} onChange={(event) => setPingId(event.target.value)}><option value="">Choose a current signal</option>{pings.map((ping) => <option value={ping.id} key={ping.id}>{playerName(ping.senderId)}: {pingLabels[ping.category]}</option>)}</select></label><button className="quiet-button" disabled={busy || !running || !pings.some((ping) => ping.id === pingId)} onClick={() => cooperate({ targetAiId: resolvedTarget, action: 'attack_ping', pingId })}>Request attack</button></div></> : <p className="small-copy">No allied AI commanders are available in this match.</p>}</details>
    <div className="team-signals"><div className="recovery-section-heading"><h3>Team signals</h3><small>Alt + click minimap: Help</small></div><div className="ping-compose"><select aria-label="Signal category" value={category} onChange={(event) => setCategory(event.target.value as TeamPing['category'])}>{Object.entries(pingLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="quiet-button" disabled={busy || !running} onClick={sendPing}>Signal camera center</button></div>{pings.map((ping) => <button className="team-signal" key={ping.id} onClick={() => world.focus(ping.xMm, ping.zMm)}><span>{pingSymbols[ping.category]}</span><b>{playerName(ping.senderId)}</b> {pingLabels[ping.category]}<small>Go to location</small></button>)}<p className="small-copy">Signals mark a coordinate for teammates. They do not reveal hidden units or terrain.</p></div>
  </section>;
}
