import { useCallback, useEffect, useRef, useState } from 'react';
import { useModalFocus } from './modalFocus';
import { balance, validateHostRecoveryResponse, validateRejoinInviteResponse, type HostRecoveryResponse, type RejoinInviteResponse, type SessionResponse } from '@frontier/shared';

export function HostRecovery({ session, refreshSession, close, openReplay, openEndpoint }: { session: SessionResponse; refreshSession: () => Promise<unknown>; close: () => void; openReplay: () => void; openEndpoint: () => void }) {
  const [recovery, setRecovery] = useState<HostRecoveryResponse | null>(null);
  const [name, setName] = useState('My frontier');
  const [notice, setNotice] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [listError, setListError] = useState('');
  const listRequest = useRef<{ controller: AbortController; promise: Promise<void> } | null>(null);
  const [load, setLoad] = useState<{ id?: string; label: string } | null>(null);
  const [invites, setInvites] = useState<Record<string, RejoinInviteResponse>>({});
  const [surrender, setSurrender] = useState<string | null>(null);
  const modal = useModalFocus(true, () => { if (!busy) close(); }), loadModal = useModalFocus<HTMLDivElement>(!!load, () => { if (!busy) setLoad(null); }), surrenderModal = useModalFocus<HTMLDivElement>(!!surrender, () => { if (!busy) setSurrender(null); });
  const editable = ['LOBBY', 'PAUSED', 'FINISHED'].includes(session.lobby.status);
  const loadData = useCallback(() => {
    if (listRequest.current) return listRequest.current.promise;
    setLoading(true); setListError('');
    const pending = { controller: new AbortController(), promise: Promise.resolve() };
    listRequest.current = pending;
    pending.promise = (async () => {
      let timedOut = false;
      const timeout = setTimeout(() => { timedOut = true; pending.controller.abort(); }, 60000);
      try {
        const response = await fetch('/api/host/recovery', { credentials: 'same-origin', cache: 'no-store', signal: pending.controller.signal });
        if (!response.ok) throw new Error(response.status === 401 || response.status === 403 ? 'Host access expired. Sign in to host controls again.' : 'Could not read saved games. Retry the list.');
        const value: unknown = await response.json();
        if (!validateHostRecoveryResponse(value)) throw new Error('Incompatible recovery information from the host.');
        if (listRequest.current === pending) setRecovery(value);
      } catch (problem) {
        if (listRequest.current === pending) setListError(timedOut ? 'Checking saved games took more than a minute. Retry the list; your saved files are unchanged.' : problem instanceof Error && problem.name !== 'AbortError' ? problem.message : 'Could not read saved games. Retry the list.');
      } finally {
        clearTimeout(timeout);
        if (listRequest.current === pending) { listRequest.current = null; setLoading(false); }
      }
    })();
    return pending.promise;
  }, []);
  useEffect(() => { void loadData(); return () => { const pending = listRequest.current; listRequest.current = null; pending?.controller.abort(); }; }, [loadData]);
  async function request(path: string, body: unknown): Promise<unknown> {
    const response = await fetch(path, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...(session.csrfToken ? { 'X-CSRF-Token': session.csrfToken } : {}) }, body: JSON.stringify(body) });
    const value = await response.json().catch(() => null) as { code?: string; message?: string } | null;
    if (!response.ok) throw new Error((value?.message ?? value?.code ?? `Host request failed (${response.status}).`).replaceAll('_', ' '));
    return value;
  }
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); setNotice(''); try { await work(); await refreshSession(); if (listRequest.current) await listRequest.current.promise; await loadData(); } catch (problem) { setError(problem instanceof Error ? problem.message : 'The host operation failed.'); } finally { setBusy(false); } }
  const playerName = (id: string) => session.lobby.players.find((player) => player.id === id)?.name ?? id;
  return <div className="dialog-overlay"><section ref={modal} className="host-recovery" role="dialog" aria-modal="true" aria-label="Host saves and recovery"><header><div><span className="eyebrow">THE HOST’S CHRONICLE</span><h2>Saves & recovery</h2></div><button className="quiet-button" aria-label="Close saves and recovery" disabled={busy} onClick={close}>×</button></header><p className="small-copy">Saves remain on the host computer. Loading restores a paused match with fresh invitations for every human slot.</p>
    <div className="recovery-status"><span>{session.lobby.status.replaceAll('_', ' ')}</span><span>{recovery ? recovery.persistence.journalHealthy === false ? 'Command journal needs attention' : 'Command journal available' : loading ? 'Reading host recovery information...' : 'Command journal status unavailable'}</span><button className="quiet-button" disabled={busy || loading} onClick={() => void loadData()}>{listError ? 'Retry list' : 'Refresh list'}</button></div>
    {error && !load && !surrender && <p className="recovery-error" role="alert">{error}</p>}{notice && <p className="recovery-notice" role="status">{notice}</p>}
    <section className="recovery-section" aria-label="Load saved game" aria-busy={loading}>
      <div className="recovery-section-heading"><h3>Load a saved game</h3><button className="quiet-button" disabled={busy || loading || !editable || !recovery?.saves.some(save => save.kind === 'auto')} title={editable ? 'Load the newest compatible autosave' : 'Pause the match before loading'} onClick={() => { setError(''); setLoad({ label: 'the latest compatible autosave' }); }}>Load latest autosave</button></div>
      {!editable && <p className="small-copy">Pause the match before replacing it with a save.</p>}
      {loading && <p className="small-copy" aria-live="polite">Checking saved games for compatibility. A large collection can take a minute. Load buttons will appear below when the check finishes.</p>}
      {listError && <p className="recovery-error" role="alert">{listError}{recovery && ' The previously loaded list is still shown below.'}</p>}
      <div className="save-list">{recovery?.saves.map(save => <article key={save.id}><div><b>{save.label}</b><small>{save.kind === 'auto' ? 'Autosave' : 'Manual'} · {new Date(save.createdAt).toLocaleString()} · {Math.floor(save.tick / balance.rules.simulationHz / 60)}m {Math.floor(save.tick / balance.rules.simulationHz) % 60}s · {Math.ceil(save.bytes / 1024)} KiB</small></div><button className="quiet-button" aria-label={`Load save ${save.label}`} disabled={busy || loading || !editable} onClick={() => { setError(''); setLoad({ id: save.id, label: save.label }); }}>Load</button></article>)}{recovery && !loading && !recovery.saves.length && <p className="small-copy">No compatible saves are available for this build.{recovery.warnings.length ? ' See unavailable saves below for the reasons.' : ' Save a match to make it available here.'}</p>}</div>
    </section>
    <div className="recovery-section-heading"><h3>Strategic commanders</h3><button className="quiet-button" disabled={busy} onClick={openEndpoint}>AI endpoint & diagnostics</button></div>
    {recovery?.persistence.lastError && <p className="recovery-error">Save warning: {recovery.persistence.lastError.replaceAll('_', ' ')}</p>}
    <div className="recovery-section"><h3>Save this match</h3><form className="manual-save" onSubmit={(event) => { event.preventDefault(); void action(async () => { await request('/api/host/save', { name: name.trim() }); setNotice('Save written successfully on the host.'); }); }}><label>SAVE NAME<input aria-label="Save name" value={name} required maxLength={64} onChange={(event) => setName(event.target.value)} /></label><button className="primary" disabled={busy || !name.trim() || !['RUNNING', 'PAUSED', 'FINISHED'].includes(session.lobby.status)}>Save match<span>↗</span></button></form><p className="small-copy">The host autosaves every 60 simulation seconds and retains the latest five valid autosaves. A disk-write failure is reported without stopping the simulation.</p></div>
    {!!recovery?.warnings.length && <details className="save-warnings"><summary>{recovery.warnings.length} unavailable save{recovery.warnings.length > 1 ? 's' : ''}</summary><p className="small-copy">These files are separate from the compatible saves listed above. Saves from an earlier gameplay build require that matching build; they are not necessarily damaged. Your files have not been removed.</p>{recovery.warnings.map((warning) => <p key={`${warning.id}-${warning.code}`}>{warning.id}: {warning.code.replaceAll('_', ' ')}</p>)}</details>}
    {!!recovery?.restoreSlots.length && <div className="recovery-section"><h3>Restore human commands</h3><p className="small-copy">Issue a fresh invitation for each person. The old match’s cookies and invitations cannot claim restored slots. Resume after the intended commanders have rejoined.</p><div className="restore-slots">{recovery.restoreSlots.map((slot) => <article key={slot.playerId}><div><b>{slot.name}{slot.hostPlayer ? ' · host-player' : ''}</b><small>{slot.claimed ? 'Slot claimed' : 'Waiting for a fresh invitation'}</small></div>{!slot.claimed && <button className="quiet-button" disabled={busy} aria-label={`Create rejoin invite for ${slot.name}`} onClick={() => void action(async () => { const response = await request('/api/host/rejoin-invite', { playerId: slot.playerId }); if (!validateRejoinInviteResponse(response)) throw new Error('Invalid rejoin invitation response.'); setInvites((current) => ({ ...current, [slot.playerId]: response })); setNotice(`Fresh invitation created for ${slot.name}.`); })}>Create invitation</button>}{invites[slot.playerId] && !slot.claimed && <div className="issued-invite"><label>REJOIN TOKEN<input aria-label={`Rejoin token for ${slot.name}`} readOnly value={invites[slot.playerId]!.token} onFocus={(event) => event.target.select()} /></label><small>Expires {new Date(invites[slot.playerId]!.expiresAt).toLocaleTimeString()}. Share only with this slot’s owner.</small>{slot.hostPlayer && <button className="primary" disabled={busy} onClick={() => void action(async () => { await request('/api/rejoin', { token: invites[slot.playerId]!.token }); setInvites((current) => { const next = { ...current }; delete next[slot.playerId]; return next; }); setNotice('Your host-player command has been restored.'); })}>Rejoin my host slot<span>↗</span></button>}</div>}</article>)}</div></div>}
    {!!recovery?.disconnected.length && <div className="recovery-section"><h3>Disconnected commanders</h3>{recovery.disconnected.map((entry) => <article className="disconnected-row" key={entry.playerId}><div><b>{playerName(entry.playerId)}</b><small>{Math.floor(entry.seconds)}s disconnected · {entry.mode === 'caretaker' ? 'Medium rule-based caretaker active' : entry.mode === 'reserved' ? 'Reservation retained' : 'Existing orders continue'}</small></div>{entry.decisionRequired ? <div className="disconnect-choices"><button className="quiet-button" disabled={busy} onClick={() => void action(async () => { await request('/api/host/disconnect-choice', { playerId: entry.playerId, choice: 'keep_reserved' }); setNotice(`${playerName(entry.playerId)} remains reserved.`); })}>Keep reserved</button><button className="quiet-button" disabled={busy} onClick={() => void action(async () => { await request('/api/host/disconnect-choice', { playerId: entry.playerId, choice: 'caretaker' }); setNotice('Caretaker control enabled.'); })}>Continue with caretaker</button><button className="quiet-button" disabled={busy} onClick={() => setSurrender(entry.playerId)}>Surrender faction</button></div> : <small>{entry.seconds >= 180 ? 'Host decision recorded.' : 'Host decisions unlock after 180 seconds.'}</small>}</article>)}</div>}
    {!!recovery?.pauseRequests?.length && <div className="recovery-section"><h3>Pause requests</h3>{recovery.pauseRequests.map((entry) => <p className="small-copy" key={`${entry.playerId}-${entry.timestamp}`}>{playerName(entry.playerId)} requested a pause at {new Date(entry.timestamp).toLocaleTimeString()}.</p>)}</div>}
    <div className="recovery-section"><h3>Completed recordings</h3><p className="small-copy">Review a completed match from each commander's recorded viewpoint. Available after the match or from the lobby.</p><button className="quiet-button" disabled={busy || !['LOBBY', 'FINISHED'].includes(session.lobby.status)} onClick={openReplay}>Open replay viewer</button></div>
    <div className="recovery-footer">{['RUNNING', 'PAUSED'].includes(session.lobby.status) && <button className="primary" disabled={busy} onClick={() => void action(async () => { await request('/api/host/pause', { paused: session.lobby.status !== 'PAUSED' }); setNotice(session.lobby.status === 'PAUSED' ? 'Match resumed.' : 'Match paused.'); })}>{session.lobby.status === 'PAUSED' ? 'Resume match' : 'Pause match'}<span>↗</span></button>}</div>
    {load && <div ref={loadModal} className="nested-confirmation" role="alertdialog" aria-modal="true" aria-label="Confirm save load"><h3>Load {load.label}?</h3><p>This replaces the current match. Unsaved progress is lost. The restored game remains paused until human slots receive fresh invitations.</p>{error && <p className="recovery-error" role="alert">{error}</p>}{busy && <p className="small-copy" role="status">Restoring the saved match. Please wait...</p>}<button className="primary" disabled={busy} onClick={() => void action(async () => { await request(load.id ? '/api/host/load' : '/api/host/load-latest', load.id ? { saveId: load.id, confirmed: true } : { confirmed: true }); setLoad(null); setInvites({}); setNotice('Save restored. Issue fresh slot invitations before resuming.'); })}>Confirm load<span>↗</span></button><button data-modal-initial-focus className="quiet-button" disabled={busy} onClick={() => setLoad(null)}>Keep current match</button></div>}
    {surrender && <div ref={surrenderModal} className="nested-confirmation" role="alertdialog" aria-modal="true" aria-label="Confirm disconnected surrender"><h3>Surrender {playerName(surrender)}?</h3><p>This eliminates the disconnected faction. Keeping the slot reserved allows its owner more time to return.</p>{error && <p className="recovery-error" role="alert">{error}</p>}<button className="primary" disabled={busy} onClick={() => void action(async () => { await request('/api/host/disconnect-choice', { playerId: surrender, choice: 'surrender' }); setSurrender(null); })}>Confirm faction surrender<span>↗</span></button><button data-modal-initial-focus className="quiet-button" disabled={busy} onClick={() => setSurrender(null)}>Keep reserved</button></div>}
  </section></div>;
}
