import { useEffect, useState } from 'react';
import { balance, ages, units, TEAM_IDENTITIES, type LobbyPlayer, type LobbyState } from '@frontier/shared';

export const identitySymbols = ['\u2571', '\u271a', '\u2303', '\u2630', '\u2573', '\u283f', '\u25c7', '\u259f', '\u2739', '\u25b3', '\u25ce'];
const colorNames = ['Blue', 'Orange', 'Teal', 'Magenta', 'Yellow', 'Red', 'Violet', 'Lime', 'White', 'Brown', 'Pink'];
type Post = (path: string, body: unknown) => Promise<void>;

export function HostLobbyOptions({ lobby, busy, post }: { lobby: LobbyState; busy: boolean; post: Post }) {
  const [seed, setSeed] = useState(lobby.hostSeed ?? '');
  useEffect(() => setSeed(lobby.hostSeed ?? ''), [lobby.hostSeed]);
  const automatic = balance.maps.sizes.find((size) => lobby.players.length <= size.factions[1]!) ?? balance.maps.sizes.at(-1)!;
  const preset = lobby.settings.teamPreset ?? 'custom';
  const humans = lobby.players.filter((player) => player.kind === 'human').length;
  return <div className="extended-lobby-options">
    <div className="lobby-option-section"><span className="eyebrow">ASSEMBLE THE SIDES</span><div className="team-presets">{([{ id: 'five_vs_five', title: '5 humans vs 5 AI', detail: 'Five humans total' }, { id: 'six_vs_five', title: '6 humans vs 5 AI', detail: 'Host + five remote people' }, { id: 'free_for_all', title: 'Free for all', detail: 'Every faction independent' }] as const).map((option) => <button key={option.id} className={preset === option.id ? 'active' : ''} aria-label={`Preset ${option.title}`} aria-pressed={preset === option.id} disabled={busy} onClick={() => void post('/api/host/lobby', { teamPreset: option.id })}><b>{option.title}</b><small>{option.detail}</small></button>)}</div><p className="small-copy">{preset === 'five_vs_five' || preset === 'six_vs_five' ? `${humans} / ${preset === 'five_vs_five' ? 5 : 6} humans assembled. This preset needs exactly ${preset === 'five_vs_five' ? 'five' : 'six'} human players and five AI before starting.` : 'Assign individual teams in the roster for mixed teams. At least two opposing factions are required.'}</p></div>
    <div className="host-row"><label>MAXIMUM AGE<select aria-label="Maximum age" disabled={busy} value={lobby.settings.maxAge??8} onChange={event=>void post('/api/host/lobby',{maxAge:Number(event.target.value)})}>{[4,5,6,7,8].map(age=><option key={age} value={age}>{ages[age]?.name}</option>)}</select></label></div>
    <div className="host-row"><label>MAP SIZE<select aria-label="Map size" value={lobby.settings.mapSize ?? 'auto'} disabled={busy} onChange={(event) => void post('/api/host/lobby', { mapSize: event.target.value })}><option value="auto">Automatic · {automatic.id}</option>{balance.maps.sizes.map((size) => <option key={size.id} value={size.id} disabled={lobby.players.length > size.factions[1]!}>{size.id} · {size.cells[0]! * balance.rules.buildingGridM}m · up to {size.factions[1]} factions</option>)}</select></label><label>MAP RESOURCE PRESET<select aria-label="Starting resource preset" value={lobby.settings.startingResourcePreset ?? 'long_war'} disabled={busy} onChange={event => void post('/api/host/lobby', { startingResourcePreset: event.target.value })}><option value="standard">Standard map resources</option><option value="long_war">Plentiful distant reserves</option></select></label></div>
    <div className="starting-resources">{balance.resourceOrder.map((resource) => <span key={resource}><b>{balance.start.resources[resource]}</b> {resource}</span>)}<small>{Object.entries(balance.start.units).map(([id, count]) => `${count} ${units[id]!.name}${count > 1 ? 's' : ''}`).join(' · ')} · Town Center + House</small></div>
    <form className="seed-form" onSubmit={(event) => { event.preventDefault(); void post('/api/host/seed', { seed: seed.trim() || null }); }}><label>PRIVATE MAP SEED<input aria-label="Private map seed" autoComplete="off" maxLength={96} placeholder="Random when empty" value={seed} onChange={(event) => setSeed(event.target.value)} /></label><button className="quiet-button" disabled={busy || seed === (lobby.hostSeed ?? '')}>Set seed</button></form><p className="small-copy">The seed is visible only to the host. Other players discover the generated frontier by exploring.</p>
    <div className="lobby-option-section"><span className="eyebrow">WHEN A COMMANDER DISCONNECTS</span><label className="checkbox-label"><input type="checkbox" checked={lobby.settings.caretakerEnabled ?? false} disabled={busy} onChange={(event) => void post('/api/host/lobby', { caretakerEnabled: event.target.checked })} />Enable medium rule-based caretaker after 30 seconds</label><p className="small-copy">Default: existing orders continue without strategic takeover. A caretaker uses ordinary resources and vision; reconnecting immediately returns control.</p><label className="checkbox-label"><input type="checkbox" checked={lobby.settings.pauseWhenNoHumans ?? true} disabled={busy} onChange={(event) => void post('/api/host/lobby', { pauseWhenNoHumans: event.target.checked })} />Pause after all humans disconnect for 30 seconds</label><p className="small-copy">Human slots remain reserved for 180 seconds. The host then chooses whether to keep the reservation, surrender, or continue with a caretaker.</p></div>
  </div>;
}

export function FactionOptions({ player, busy, post }: { player: LobbyPlayer; busy: boolean; post: Post }) {
  return <div className="faction-options"><label>Banner<select aria-label={`${player.name} color and pattern`} value={player.pattern ?? 0} disabled={busy} onChange={(event) => void post('/api/host/identity', { playerId: player.id, pattern: Number(event.target.value) })}>{TEAM_IDENTITIES.map(({ name }, index) => <option value={index} key={name}>{identitySymbols[index]} {name} · {colorNames[index]}</option>)}</select></label>{player.kind === 'ai' && <><label>Difficulty<select aria-label={`${player.name} difficulty`} value={player.difficulty ?? 'medium'} disabled={busy} onChange={(event) => void post('/api/host/ai', { playerId: player.id, difficulty: event.target.value, personality: player.personality ?? 'builder' })}>{['easy', 'medium', 'hard'].map((difficulty) => <option key={difficulty}>{difficulty}</option>)}</select></label><label>Personality<select aria-label={`${player.name} personality`} value={player.personality ?? 'builder'} disabled={busy} onChange={(event) => void post('/api/host/ai', { playerId: player.id, difficulty: player.difficulty ?? 'medium', personality: event.target.value })}>{['builder', 'raider', 'marshal', 'steward', 'diplomat'].map((personality) => <option key={personality}>{personality}</option>)}</select></label></>}</div>;
}
