type Schema = Record<string, unknown>;
const number = { type: 'number', minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const integer = { ...number, type: 'integer' };
const positive = { ...number, exclusiveMinimum: 0 };
const positiveInteger = { ...integer, minimum: 1 };
const bool = { type: 'boolean' };
const string = { type: 'string', minLength: 1, maxLength: 200 };
const id = { ...string, maxLength: 96, pattern: '^[a-z][a-z0-9_]*$' };
const ageNumber = { type: 'integer', minimum: 1, maximum: 8 };
const list = (items: Schema, minItems = 0, maxItems = 1000): Schema => ({ type: 'array', items, minItems, maxItems });
const unique = (items: Schema, minItems = 0, maxItems = 1000): Schema => ({ ...list(items,minItems,maxItems), uniqueItems: true });
const object = (properties: Record<string, Schema>, required = Object.keys(properties)): Schema => ({ type: 'object', additionalProperties: false, properties, required });
const resource = { enum: ['food','wood','gold','stone'] };
const cost = object({ food: integer, wood: integer, gold: integer, stone: integer });
const resourceCounts = object({ food: positiveInteger, wood: positiveInteger, gold: positiveInteger, stone: positiveInteger });
const forestBelts = object({targetDepthM:{...positiveInteger,minimum:18,maximum:30},minimumDepthM:{...positiveInteger,minimum:18,maximum:30},maximumDepthM:{...positiveInteger,minimum:18,maximum:30},minimumOpenings:{const:2},preferredOpenings:{const:3},approachLengthM:{...positiveInteger,minimum:24,maximum:48},territoryCellsBySize:object({small:{const:2},medium:{const:3},large:{const:4}})});
const armor = object({ melee: integer, pierce: integer, crush: integer });
const damageType = { enum: ['melee','pierce','crush'] };
const tags = { enum: ['worker','light','melee','cavalry','infantry','anti_cavalry','archer','ranged','anti_archer','armored','siege','anti_building','area_attack','building','wall','construct','colossal'] };
const requirements = { requiredTechnologies:unique(id), requiredBuildings:unique(id), maxPerPlayer:positiveInteger };
const launchHeight={...number,minimum:.001,maximum:100};
const turret = object({attack:positiveInteger,attackType:damageType,bonusDamage:object({cavalry:integer,archer:integer,building:integer,siege:integer,colossal:integer},[]),rangeM:positive,attackCooldownSeconds:positive,projectileSpeedMps:positive,projectileLaunchHeightM:launchHeight},['attack','attackType','bonusDamage','rangeM','attackCooldownSeconds','projectileSpeedMps']);
const common = { id, name:string, minAge:ageNumber, cost, maxHp:positiveInteger, attack:integer, attackType:damageType, rangeM:number, visionM:positive, armor, tags:unique(tags,1), attackCooldownSeconds:number, projectileSpeedMps:number };
const unitRequired = [...Object.keys(common),'producedAt','minRangeM','moveSpeedMps','trainSeconds','population','bonusDamage','collisionRadiusM','canGarrison'];
const buildingRequired = [...Object.keys(common),'buildSeconds','footprintCells','populationProvided','garrisonCapacity','dropOffResources','produces'];
const unitsSchema = object({ ...common, ...requirements, projectileLaunchHeightM:launchHeight, producedAt:id, minRangeM:number, moveSpeedMps:positive, trainSeconds:positive, population:positiveInteger, bonusDamage:object({ cavalry:integer, archer:integer, building:integer, siege:integer, colossal:integer },[]), collisionRadiusM:positive, canGarrison:bool, carryCapacity:positiveInteger, areaDamageBands:list(object({radiusM:positive,multiplier:{...number,maximum:1}}),1,8), deploySeconds:positive, packSeconds:positive,windupSeconds:positive,ammunitionCost:cost,mobileGarrisonCapacity:positiveInteger,turret,wardDepletionMultiplier:positiveInteger },unitRequired);
const buildingsSchema = object({ ...common, ...requirements, projectileLaunchHeightM:launchHeight, family:{enum:['citadel','wall','gate']},tier:positiveInteger,familyCap:positiveInteger,upgradeFrom:id,upgradeSeconds:positive,weaponPorts:{...positiveInteger,maximum:4},wardEligible:bool,wallMaterial:{enum:['palisade','stone','bastion','runestone','titan','eternal']}, attackType:{ enum:['melee','pierce','crush',null] }, buildSeconds:positive, footprintCells:{...list({...positiveInteger,maximum:32},2,2)}, populationProvided:integer, garrisonCapacity:integer, dropOffResources:unique(resource,0,4), produces:unique(id), maxPerPlayerByAge:object({'1':integer,'2':integer,'3':integer,'4':integer,'5':integer,'6':integer,'7':integer,'8':integer},['1','2','3','4']), foodCapacity:positiveInteger, maxActiveGatherers:positiveInteger, reseedCost:cost, reseedSeconds:positive, wallEquivalentCells:positiveInteger, defaultGateMode:{const:'AUTO'}, gatePassageWidthM:positive, autoOpenDistanceM:positive, autoCloseDelaySeconds:positive },buildingRequired);
const modifierStats = ['attack','maxHp','rangeM','moveSpeedMps','carryCapacity','armor.melee','armor.pierce','armor.crush','bonusDamage.cavalry','bonusDamage.archer','bonusDamage.building','bonusDamage.siege','bonusDamage.colossal','constructionRate','foodCapacity','gatherRate.forage','gatherRate.wood','gatherRate.gold','gatherRate.stone','gatherRate.farm'];
const technologiesSchema = object({id,name:string,minAge:ageNumber,researchedAt:id,cost,researchSeconds:positive,prerequisites:unique(id),effects:list(object({targets:unique(id,1),stat:{enum:modifierStats},operation:{enum:['add','add_base_fraction']},value:number}),1)});
const agePrerequisite = {oneOf:[object({kind:{const:'completed_buildings'},types:unique(id,1)}),object({kind:{const:'distinct_completed_building_types'},types:unique(id,1),count:positiveInteger})]};
const agesSchema = object({id:ageNumber,name:string,cost,researchSeconds:number,requiredAge:{anyOf:[ageNumber,{type:'null'}]},prerequisites:list(agePrerequisite)});
const rulesSchema = object({
  combatAcquisitionRadiusM:{...positive,maximum:64},idleGatherRadiusM:{...positive,maximum:64},
  simulationHz:positiveInteger,authoritativeFrameMs:{enum:[50,300]},replicationHz:positiveInteger,remoteHumanLimit:{const:5},hostPlayerLimit:{const:1},aiLimit:{const:5},factionLimit:{const:11},defaultPopulationLimit:{enum:[80,120,200]},populationOptions:{const:[80,120,200]},buildingGridM:positive,treeBuildingClearanceM:{...positive,maximum:16},nonTreeBuildingClearanceM:{...positive,maximum:16},navigationGridM:positive,fogGridM:positive,resourceScale:positiveInteger,positionUnitsPerM:positiveInteger,queueWaitingLimit:positiveInteger,orderQueueLimit:positiveInteger,maxWallSegmentsPerCommand:{...positiveInteger,maximum:64},maxNonWallBuildingsPerPlayer:positiveInteger,maxWallEquivalentCellsPerPlayer:positiveInteger,maxResourceNodes:positiveInteger,constructionWorkerMultipliers:list(positive,5,5),foundationStartingHpFraction:{...positive,maximum:1},unfinishedCancelRefundFraction:{...number,maximum:1},startedJobRemainingRefundFraction:{...number,maximum:1},repairHpPerWorkerSecond:positive,repairFullHpCostFraction:{...positive,maximum:1},monumentHoldSeconds:positive,carryCapacity:positiveInteger,garrisonHealHpPerSecond:positive,garrisonEjectionDamageFraction:{...positive,maximum:1},demolitionSeconds:positive,
  gatherPerWorkingSecond:object({forage:positive,farm:positive,wood:positive,gold:positive,stone:positive}),market:object({tradeLot:positiveInteger,sellGold:positiveInteger,buyGold:positiveInteger,tributeFeeFraction:{...number,maximum:1}})
});
const difficultySchema = object({strategicIntervalSeconds:positive,tacticalIntervalSeconds:positive,reactionDelaySeconds:number,initialBaseAssaultNotBeforeSeconds:number,resourceMultiplier:{const:1},damageMultiplier:{const:1},omniscient:{const:false}});
const rulePolicySchema=object({targetWorkers:{...integer,minimum:6,maximum:150},housingBuffer:{...integer,minimum:1,maximum:20},workerReserve:{...integer,minimum:1,maximum:6},scoutIntervalSeconds:positive,retreatHpFraction:{...number,maximum:1},baseTargetsByAge:list({...integer,minimum:1,maximum:3},4,4),armyTargetsByAge:list({...integer,maximum:200},4,4)});
const personalityPolicySchema=object({resourceWeights:object({food:{...integer,maximum:100},wood:{...integer,maximum:100},gold:{...integer,maximum:100},stone:{...integer,maximum:100}}),preferredUnits:unique(id,1,11),infrastructure:unique(id,0,20),assistAllies:bool,fortify:bool,raid:bool});
export const contentSchema = object({
  schemaVersion:{const:1},status:string,resourceOrder:{const:['food','wood','gold','stone']},ages:list(agesSchema,4,8),units:list(unitsSchema,11,19),buildings:list(buildingsSchema,20,35),technologies:list(technologiesSchema,29,41),rules:rulesSchema,
  start:object({age:ageNumber,resources:cost,units:{type:'object',propertyNames:id,additionalProperties:integer},buildings:{type:'object',propertyNames:id,additionalProperties:integer}}),
  maps:object({types:{const:['open_frontier','river_divide']},sizes:list(object({id:{enum:['small','medium','large']},cells:list({...positiveInteger,maximum:320},2,2),factions:list({...positiveInteger,maximum:11},2,2)}),3,3),spawnResourceMinimum:cost,resourceNodes:object({starting:resourceCounts,expansion:resourceCounts,forestPatchLimit:{...positiveInteger,maximum:30}}),maxGenerationAttempts:positiveInteger,startingTravelVariationFraction:{...number,maximum:1},forestNavigationCellM:{...positiveInteger,maximum:3},forestBelts,naturalBarriers:object({minimumRouteWidthM:{...positiveInteger,minimum:32,maximum:64},valleyWidthM:{...positiveInteger,minimum:48,maximum:96},stagingRegionM:{...positiveInteger,minimum:40,maximum:64},minimumStartSeparationM:{...positiveInteger,minimum:112,maximum:160},ridgeHeightM:{...positiveInteger,minimum:8,maximum:20}})}),
  ai:object({maxConcurrent:{...positiveInteger,maximum:5},timeoutSeconds:positive,maxObservationAgeSeconds:positive,goalTtlSeconds:positive,maxGoals:{...positiveInteger,maximum:8},maxOutputTokens:positiveInteger,targetOutputTokens:positiveInteger,maxAdaptiveIntervalSeconds:positive,personalities:{const:['builder','raider','marshal','steward','diplomat']},difficulty:object({easy:difficultySchema,medium:difficultySchema,hard:difficultySchema}),rulePolicies:object({easy:rulePolicySchema,medium:rulePolicySchema,hard:rulePolicySchema}),personalityPolicies:object({builder:personalityPolicySchema,raider:personalityPolicySchema,marshal:personalityPolicySchema,steward:personalityPolicySchema,diplomat:personalityPolicySchema})})
});



export const legendaryExpansionSchema = object({schemaVersion:{const:1},status:{const:'PROPOSED_UNBALANCED_INITIAL_CONTENT'},rulesetId:{const:'legendary_ages_v1'},ages:list(agesSchema,4,4),units:list(unitsSchema,8,8),buildings:list(buildingsSchema,15,15),technologies:list(technologiesSchema,12,12),wards:object({radiusM:positive,maxTargets:positiveInteger,quietSeconds:positive,byAge:object(Object.fromEntries(['6','7','8'].map(age=>[age,object({citadel:positiveInteger,gate:positiveInteger,wall:positiveInteger,recoveryPerSecond:positive})])))}),longWar:object({perFactionNonStartingMinimum:object({wood:positiveInteger,gold:positiveInteger,stone:positiveInteger}),outerExpansionFraction:{const:.5},preservePerNodeYields:{const:true},minimumRoutes:{const:2},minimumRouteWidthM:{...positive,minimum:32},forestOpeningWidthM:{...positive,minimum:48},maxResourceNodes:{const:32000}})});
