import Ajv2020, { type ErrorObject, type ValidateFunction } from 'ajv/dist/2020.js';
import commandSchema from '../../../schemas/client-command.schema.json';
import aiPlanSchema from '../../../schemas/ai-plan.schema.json';
import rawBalance from '../../../data/balance.v1.json';
import { MAX_WORLD_ENTITIES, SIMULATION_FRAME_PHASES } from './types.js';
import type { AiPlan, BootstrapRequest, ClientCommandEnvelope, ClientSocketMessage, HostRecoveryResponse, JoinRequest, LoadedRequest, LobbyConfigRequest, LobbyState, PauseRequest, PlayerView, PlayerViewDelta, ReadyRequest, RejoinInviteResponse, ReplayListResponse, ReplayOpenResponse, ReplayStepResponse, ServerSocketMessage, SessionResponse, SnapshotChunk, DeltaChunk, TeamAssignmentRequest } from './types.js';
import type {EndpointSettings,EndpointUpdateRequest,EndpointStateResponse,EndpointProbeResponse,EndpointDiagnosticsResponse,ChatRequest,PingRequest,CooperationRequest,ChatStateResponse} from './types.js';
import type {AiModelCatalogResponse,AiModelUpsertRequest,AiModelAssignmentRequest,AssistantPreferences,AssistantStateResponse,AssistantOptionsResponse,AssistantReleaseRequest} from './types.js';

export const ajv = new Ajv2020({ strict: true, allErrors: false, discriminator: true, code: { source: true, esm: true }, ownProperties: true, coerceTypes: false, useDefaults: false, removeAdditional: false });

import { protect, type StrictValidator } from './validation-safety.js';
import { validViewTiming } from './view-timing.js';
export const validateClientCommand = protect(compileNamed<ClientCommandEnvelope>('validateClientCommand', commandSchema));
export const validateAiPlan = protect(compileNamed<AiPlan>('validateAiPlan', aiPlanSchema), plan => plan.goals.every(goal => goal.kind !== 'economy' || Object.values(goal.weights).reduce((sum, n) => sum + n, 0) === 100));
const id = { type: 'string', minLength: 1, maxLength: 96, pattern: '^[A-Za-z0-9_-]+$' };
const textToken = { type: 'string', minLength: 1, maxLength: 256, pattern: '^[A-Za-z0-9_-]+$' };
const object = (properties: Record<string, unknown>, required = Object.keys(properties)) => ({ type: 'object', additionalProperties: false, properties, required });
const lobbySettingExtras={mapSize:{enum:['auto','small','medium','large']},rulesetId:{enum:['classic_v1','legendary_ages_v1']},maxAge:{enum:[4,5,6,7,8]},startingResourcePreset:{enum:['standard','long_war']},pauseWhenNoHumans:{type:'boolean'},teamPreset:{enum:['custom','free_for_all','five_vs_five','six_vs_five']},tutorial:{type:'boolean'}};
export const validateEmptyRequest = protect(compileNamed<Record<string,never>>('validateEmptyRequest',object({})));
export const validatePauseRequest = protect(compileNamed<PauseRequest>('validatePauseRequest',object({paused:{type:'boolean'}})));
export const validateTeamAssignmentRequest = protect(compileNamed<TeamAssignmentRequest>('validateTeamAssignmentRequest',object({playerId:id,teamId:id})));
const loadedProperties = { contentHash: { type: 'string', minLength: 1, maxLength: 128 }, matchId: id, matchEpoch: { type: 'integer', minimum: 1, maximum: 2147483647 } };
export const validateJoin = protect(compileNamed<JoinRequest>('validateJoin', object({ name: { type: 'string', minLength: 1, maxLength: 32, pattern: '\\S' }, inviteCode: textToken, hostPlayer: { type: 'boolean' } }, ['name', 'inviteCode'])));
export const validateReady = protect(compileNamed<ReadyRequest>('validateReady', object({ ready: { type: 'boolean' } })));
export const validateBootstrap = protect(compileNamed<BootstrapRequest>('validateBootstrap', object({ token: textToken })));
export const validateLoaded = protect(compileNamed<LoadedRequest>('validateLoaded', object(loadedProperties)));
export const validateLobbyConfig = protect(compileNamed<LobbyConfigRequest>('validateLobbyConfig', { ...object({ aiCount: { type: 'integer', minimum: 0, maximum: 5 }, mapType: { enum: ['open_frontier', 'river_divide'] }, populationLimit: { enum: [80, 120, 200] }, sharedVision: { type: 'boolean' },monumentVictory:{type:'boolean'},caretakerEnabled:{type:'boolean'},...lobbySettingExtras }, []), minProperties: 1 }));
export const validateClientSocketMessage = protect(compileNamed<ClientSocketMessage>('validateClientSocketMessage', { oneOf: [{ $ref: 'urn:open-frontiers:client-command:v2' }, object({ type: { const: 'resync' } }), object({ type: { const: 'loaded' }, ...loadedProperties })] }));

/** Transport callers enforce their byte limit before parsing. Errors contain no submitted data. */
export function parseClientSocketMessage(text: string): ClientSocketMessage | undefined {
  if (new TextEncoder().encode(text).length > 16384) return undefined;
  try { const value: unknown = JSON.parse(text); return validateClientSocketMessage(value) ? value : undefined; } catch { return undefined; }
}

const nonnegativeInteger = { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const nonnegativeNumber = { type: 'number', minimum: 0, maximum: Number.MAX_SAFE_INTEGER };
const progress = { type: 'number', minimum: 0, maximum: 1 };
const flag = { type: 'boolean' };
const array = (items: unknown, maxItems: number) => ({ type: 'array', items, maxItems });
const resource = { enum: ['food', 'wood', 'gold', 'stone'] };
const resources = object({ food: nonnegativeInteger, wood: nonnegativeInteger, gold: nonnegativeInteger, stone: nonnegativeInteger });
const publicPlayerProperties = {
  id, name: { type: 'string', minLength: 1, maxLength: 32 }, teamId: id,
  color: { type: 'string', pattern: '^#[a-fA-F0-9]{6}$' }, kind: { enum: ['human', 'ai'] },
  hostPlayer: flag, ready: flag, connected: flag, defeated: flag,
  age:{type:'integer',minimum:1,maximum:8},
  pattern:{type:'integer',minimum:0,maximum:10},
  controlMode:{enum:['human','disconnected','caretaker','ai']},
  aiMode:{enum:['model','fallback']},
  aiModelId:id,assistant:object({modelId:{anyOf:[id,{type:'null'}]},enabled:flag}),
  difficulty: { enum: ['easy', 'medium', 'hard'] }, personality: { enum: ['builder', 'raider', 'marshal', 'steward', 'diplomat'] },
};
const publicPlayer = object(publicPlayerProperties, ['id','name','teamId','color','kind']);
const lobbyPlayer = object(publicPlayerProperties, ['id','name','teamId','color','kind','hostPlayer','ready','connected']);
const settings = object({ aiCount: { type:'integer',minimum:0,maximum:5 }, mapType:{enum:['open_frontier','river_divide']},populationLimit:{enum:[80,120,200]},sharedVision:flag,monumentVictory:flag,caretakerEnabled:flag,...lobbySettingExtras },['aiCount','mapType','populationLimit','sharedVision']);
const lobbySchema = object({ status:{enum:['SETUP','LOBBY','LOADING','COUNTDOWN','RUNNING','PAUSED','FINISHED','ARCHIVED']},players:array(lobbyPlayer,11),settings,canStart:flag,inviteCode:textToken,hostSeed:{anyOf:[{type:'string',minLength:1,maxLength:256},{type:'null'}]},pauseReason:{enum:['host','no_humans','overload']},pauseRequests:array(object({playerId:id,timestamp:nonnegativeInteger}),6) },['status','players','settings','canStart']);
const job = {oneOf:([
  ['train',commandSchema.$defs.train.properties.unitType.enum,['waiting','active','population_blocked','exit_blocked']],
  ['research',commandSchema.$defs.research.properties.technologyId.enum,['waiting','active','prerequisite_blocked']],
  ['age',['age_2','age_3','age_4','age_5','age_6','age_7','age_8'],['waiting','active','prerequisite_blocked']],
] as const).map(([kind,typeIds,states])=>({...object({id,kind:{const:kind},typeId:{enum:typeIds},progress,state:{enum:states},started:flag,blockedReason:{type:'string',minLength:1,maxLength:96}},['id','kind','typeId','progress','state']),if:{properties:{state:{const:'prerequisite_blocked'}},required:['state']},then:{properties:{blockedReason:{type:'string',minLength:1,maxLength:96}},required:['blockedReason']}}))};
const terrainRectangle={id,xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},widthMm:{type:'integer',minimum:1,maximum:640000},depthMm:{type:'integer',minimum:1,maximum:640000}};
const elevation={type:'integer',minimum:-20000,maximum:20000};
const terrainRegion={oneOf:[object({...terrainRectangle,kind:{enum:['water','bridge','plateau','cliff','hill','ridge']},elevationMm:elevation}),object({...terrainRectangle,kind:{const:'ramp'},axis:{enum:['x','z']},startElevationMm:elevation,endElevationMm:elevation})]};
const notification=object({id,tick:nonnegativeInteger,code:{type:'string',minLength:1,maxLength:96},entityId:id},['id','tick','code']);
const ledgerEntry=object({tick:nonnegativeInteger,reason:{type:'string',minLength:1,maxLength:96},resource,deltaMilli:{type:'integer',minimum:-Number.MAX_SAFE_INTEGER,maximum:Number.MAX_SAFE_INTEGER},balanceMilli:nonnegativeInteger,entityId:id},['tick','reason','resource','deltaMilli','balanceMilli']);
const finalStatistics=object({playerId:id,collected:resources,spent:resources,lostCargo:resources,unitsTrained:nonnegativeInteger,unitsLost:nonnegativeInteger,buildingsBuilt:nonnegativeInteger,buildingsLost:nonnegativeInteger,ageTicks:object({'1':nonnegativeInteger,'2':nonnegativeInteger,'3':nonnegativeInteger,'4':nonnegativeInteger,'5':nonnegativeInteger,'6':nonnegativeInteger,'7':nonnegativeInteger,'8':nonnegativeInteger},[]),fallbackTicks:nonnegativeInteger,modelReadyTicks:nonnegativeInteger,inferenceFailures:nonnegativeInteger});
const facingMilliRad={type:'integer',minimum:-3142,maximum:3142};
// The required kind tags are disjoint, so dispatch retains exactly-one-branch semantics.
const visualAction={type:'object',discriminator:{propertyName:'kind'},oneOf:[object({kind:{enum:['idle','move','carry']},startedTick:nonnegativeInteger}),object({kind:{enum:['gather_food','gather_wood','mine','build','repair']},startedTick:nonnegativeInteger,facingMilliRad},['kind','startedTick']),object({kind:{const:'attack'},startedTick:nonnegativeInteger,durationTicks:{type:'integer',minimum:1,maximum:1200},facingMilliRad},['kind','startedTick','durationTicks'])]};
const effect={...object({id,tick:nonnegativeInteger,kind:{enum:['impact','hit','death']},projectileKind:{enum:['arrow','stone']},xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},typeId:id,entityId:id,ownerId:id,visualAge:{type:'integer',minimum:1,maximum:8},visualTier:{enum:['base','veteran','elite']},rotation:{enum:[0,90,180,270]}},['id','tick','kind','xMm','zMm']),dependentRequired:{ownerId:['typeId','entityId','visualAge','visualTier'],visualAge:['ownerId'],visualTier:['ownerId'],rotation:['ownerId']},if:{properties:{kind:{const:'hit'}},required:['kind']},then:{properties:{ownerId:id},required:['ownerId']},allOf:[{if:{properties:{kind:{const:'impact'}},required:['kind']},then:{properties:{projectileKind:{enum:['arrow','stone']},typeId:{enum:commandSchema.$defs.train.properties.unitType.enum},entityId:false,ownerId:false,visualAge:false,visualTier:false,rotation:false},required:['projectileKind']},else:{properties:{projectileKind:false}}}]};
const motionTrace=object({complete:flag,points:{...array(object({tick:nonnegativeInteger,xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},yMm:{type:'integer',minimum:-20000,maximum:100000}},['tick','xMm','zMm']),16),minItems:1}});
const visualTrace=object({complete:flag,fromTick:nonnegativeInteger,points:{...array(object({tick:nonnegativeInteger,visualAction,gateOpen:flag},['tick']),13),minItems:1}});
const entity = {...object({
  motionTrace,visualTrace,pendingConstruction:flag,
  upgrade:object({jobId:id,targetTypeId:{enum:commandSchema.$defs.upgrade_structure.properties.targetTypeId.enum},progress,started:flag,state:{enum:['waiting','active']}}),
  ward:object({current:nonnegativeNumber,max:nonnegativeNumber,supportId:id},['current','max']),weaponCooldowns:array(nonnegativeInteger,4),ammoAffordable:flag,windup:object({remainingTicks:nonnegativeInteger,aim:commandSchema.$defs.move.properties.target},['remainingTicks']),
  id,kind:{enum:['unit','building','resource']},typeId:id,ownerId:{...id,type:['string','null']},
  xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},hp:nonnegativeNumber,maxHp:nonnegativeNumber,
  progress,resource,amount:nonnegativeNumber,forest:object({patchId:id,cellMm:{const:rawBalance.maps.forestNavigationCellM*rawBalance.rules.positionUnitsPerM}}),forestIntentId:id,workTargetId:id,cargo:object({resource:{anyOf:[resource,{type:'null'}]},amount:nonnegativeNumber}),
  order:{type:'string',maxLength:64},queue:array(job,6),ghost:flag,rotation:{enum:[0,90,180,270]},stance:{enum:['aggressive','defensive','stand_ground']},gateMode:{enum:['AUTO','LOCKED','OPEN']},gateOpen:flag,garrisoned:array(id,24),
  taskState:{enum:['idle','moving','gathering','returning','building','repairing','blocked']},queuedOrderCount:{type:'integer',minimum:0,maximum:16},blockedReason:{type:'string',minLength:1,maxLength:96},farmState:{enum:['ready','exhausted','reseeding']},farmerAssigned:flag,reseedProgress:progress,demolitionTicksRemaining:nonnegativeInteger,
  rally:commandSchema.$defs.move.properties.target,
  garrisonedIn:id,deploymentState:{enum:['packed','deploying','deployed','packing']},deploymentProgress:progress,lastSeenTick:nonnegativeInteger,
  visualAge:{type:'integer',minimum:1,maximum:8},visualTier:{enum:['base','veteran','elite']},visualAction,
},['id','kind','typeId','ownerId','xMm','zMm','hp','maxHp']),allOf:[{if:{properties:{pendingConstruction:{}},required:['pendingConstruction']},then:{properties:{kind:{const:'building'}}}},{if:{properties:{forest:{}},required:['forest']},then:{properties:{kind:{const:'resource'},resource:{const:'wood'}},required:['resource']}},{if:{anyOf:[{properties:{forestIntentId:{}},required:['forestIntentId']},{properties:{workTargetId:{}},required:['workTargetId']}]},then:{properties:{kind:{const:'unit'},typeId:{const:'villager'}}}}]};
// Keep the raw fragments above self-contained for saves. Real nested references let Ajv's
// default inlineRefs policy share the large view validators without changing global options.
function privateViewFragment(name:string,schema:object) {
  const $id=`urn:frontier:private-view:${name}:v1`;
  ajv.addSchema({...schema,$id});
  return {$ref:$id};
}
const viewTickRef=privateViewFragment('tick',nonnegativeInteger);
const viewActionRef=privateViewFragment('action',{
  ...visualAction,
  oneOf:visualAction.oneOf.map(branch=>({...branch,properties:{...branch.properties,startedTick:viewTickRef}})),
});
const viewEntityRef=privateViewFragment('entity',{...entity,properties:{...entity.properties,visualAction:viewActionRef}});
// Keep the hot numeric-array loops in a small validator. The nested scalar ref
// makes Ajv share the fog function while still inlining every cell constraint.
const viewFogCellRef=privateViewFragment('fog-cell',{...nonnegativeInteger,maximum:102399});
const viewFogRef=privateViewFragment('fog',object({visible:array(viewFogCellRef,102400),explored:array(viewFogCellRef,102400)}));
const viewSchema = object({
  rulesetId:{enum:['classic_v1','legendary_ages_v1']},maxAge:{enum:[4,5,6,7,8]},startingResourcePreset:{enum:['standard','long_war']},
  protocolVersion:{const:2},...loadedProperties,tick:nonnegativeInteger,sequence:nonnegativeInteger,playerId:id,status:{enum:['LOADING','COUNTDOWN','RUNNING','PAUSED','FINISHED']},
  simulationSpeed:{type:'number',minimum:.1,maximum:1},
  publicationIntervalMs:{enum:[100,150,200,300,450,600]},committedTimeMs:nonnegativeInteger,frameRevision:nonnegativeInteger,authoritativeIntervalMs:{enum:[50,300,450,600]},
  map:object({widthMm:{type:'integer',minimum:1,maximum:640000},heightMm:{type:'integer',minimum:1,maximum:640000},fogCellMm:{type:'integer',minimum:1,maximum:640000},type:{enum:['open_frontier','river_divide']},generatorVersion:{type:'string',minLength:1,maxLength:64},terrain:array(terrainRegion,64)},['widthMm','heightMm','fogCellMm']),
  self:object({lastCommandSequence:nonnegativeInteger,resources,age:{type:'integer',minimum:1,maximum:8},population:nonnegativeInteger,populationCap:nonnegativeInteger,populationLimit:{enum:[80,120,200]},reservedPopulation:nonnegativeInteger,technologies:{...array({enum:commandSchema.$defs.research.properties.technologyId.enum},41),uniqueItems:true},autoReseed:flag,idleWorkers:nonnegativeInteger,incomePerMinute:resources,notifications:array(notification,50),recentLedger:array(ledgerEntry,100)},['lastCommandSequence','resources','age','population','populationCap','populationLimit','reservedPopulation']),
  players:array(publicPlayer,11),entities:array(viewEntityRef,MAX_WORLD_ENTITIES),fog:viewFogRef,
  projectiles:array(object({id,kind:{enum:['arrow','stone']},xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},yMm:{type:'integer',minimum:-20000,maximum:100000},motionTrace,sourceTypeId:{enum:commandSchema.$defs.train.properties.unitType.enum},impactWarning:object({xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},radiusMm:{type:'integer',minimum:1,maximum:10000},hitTick:nonnegativeInteger})},['id','kind','xMm','zMm','yMm']),4096),
  effects:array(effect,4096),
  monuments:array(object({id,ownerId:id,xMm:{type:'integer',minimum:0,maximum:640000},zMm:{type:'integer',minimum:0,maximum:640000},remainingTicks:nonnegativeInteger}),11),
  ageAnnouncements:array(object({playerId:id,age:{enum:[2,3,4,5,6,7,8]},tick:nonnegativeInteger}),77),
  result:object({winnerTeamId:{anyOf:[id,{type:'null'}]},reason:{type:'string',minLength:1,maxLength:128},durationTicks:nonnegativeInteger,statistics:array(finalStatistics,11)},['winnerTeamId','reason']),
},['protocolVersion','contentHash','matchId','matchEpoch','tick','sequence','playerId','status','map','self','players','entities','fog']);
const {entities:_entities,fog:_fog,...deltaHeader}=viewSchema.properties;
const deltaSchema=object({...deltaHeader,baseSequence:nonnegativeInteger,creates:array(viewEntityRef,MAX_WORLD_ENTITIES),updates:array(viewEntityRef,MAX_WORLD_ENTITIES),conceals:array(id,MAX_WORLD_ENTITIES),removals:array(id,MAX_WORLD_ENTITIES),fog:object({visibleAdded:array({...nonnegativeInteger,maximum:102399},102400),visibleRemoved:array({...nonnegativeInteger,maximum:102399},102400),exploredAdded:array({...nonnegativeInteger,maximum:102399},102400)})},[...viewSchema.required.filter(key=>key!=='entities'&&key!=='fog'),'baseSequence','creates','updates','conceals','removals','fog']);
const chunkSchema=object({type:{const:'snapshot_chunk'},transferId:id,protocolVersion:{const:2},...loadedProperties,playerId:id,sequence:nonnegativeInteger,index:{type:'integer',minimum:0,maximum:511},count:{type:'integer',minimum:1,maximum:512},byteLength:{type:'integer',minimum:1,maximum:16777216},sha256:{type:'string',pattern:'^[a-f0-9]{64}$'},data:{type:'string',minLength:4,maxLength:43692,pattern:'^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'}});
const deltaChunkSchema=object({...chunkSchema.properties,type:{const:'delta_chunk'},baseSequence:nonnegativeInteger});
const receipt = object({status:{enum:['accepted','rejected']},clientCommandId:{type:'string',maxLength:96,pattern:'^[A-Za-z0-9_-]*$'},code:{type:'string',minLength:1,maxLength:96},tick:nonnegativeInteger,sequence:nonnegativeInteger,missingResources:resources},['status','clientCommandId','tick','sequence']);
/** Node-only save compilation imports these strict structures; never exported by the browser entry. */
const savedEntity:typeof entity={...entity,properties:{...entity.properties,visualTrace:false,pendingConstruction:false}};
export const saveSchemaFragments={entity:savedEntity,terrainRegion,publicPlayer,receipt,notification,ledgerEntry,finalStatistics,visualAction,effect};
const sessionSchema = object({protocolVersion:{const:2},contentHash:loadedProperties.contentHash,csrfToken:{anyOf:[{type:'string',maxLength:256},{type:'null'}]},host:flag,playerId:id,lobby:lobbySchema},['protocolVersion','contentHash','csrfToken','host','lobby']);
const saveSummary=object({id:{type:'string',pattern:'^(auto|manual)_[0-9]{13}_[a-f0-9]{16}$',maxLength:40},kind:{enum:['auto','manual']},label:{type:'string',minLength:1,maxLength:64},createdAt:{type:'string',pattern:'^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\\.[0-9]{3}Z$',maxLength:24},tick:nonnegativeInteger,bytes:nonnegativeInteger});
export const validateHostRecoveryResponse=protect(compileNamed<HostRecoveryResponse>('validateHostRecoveryResponse',object({saves:array(saveSummary,512),warnings:array(object({id,code:{type:'string',minLength:1,maxLength:256}}),1024),persistence:object({lastSave:saveSummary,lastError:{type:'string',minLength:1,maxLength:256},journalHealthy:flag},['journalHealthy']),disconnected:array(object({playerId:id,seconds:nonnegativeInteger,decisionRequired:flag,mode:{enum:['grace','reserved','caretaker']}}),6),restoreSlots:array(object({playerId:id,name:{type:'string',minLength:1,maxLength:32},hostPlayer:flag,claimed:flag}),6),pauseRequests:array(object({playerId:id,timestamp:nonnegativeInteger}),6)},['saves','warnings','persistence','disconnected','restoreSlots'])));
export const validateRejoinInviteResponse=protect(compileNamed<RejoinInviteResponse>('validateRejoinInviteResponse',object({playerId:id,token:{type:'string',pattern:'^[A-Za-z0-9_-]{43}$'},expiresAt:nonnegativeInteger})));
const replayId={type:'string',pattern:'^replay_[0-9]{13}_[a-f0-9]{16}$',maxLength:40};
const replaySummary=object({id:replayId,createdAt:saveSummary.properties.createdAt,startTick:nonnegativeInteger,endTick:nonnegativeInteger,endOrdinal:nonnegativeInteger,bytes:nonnegativeInteger});
export const validateReplayListResponse=protect(compileNamed<ReplayListResponse>('validateReplayListResponse',object({recordings:array(replaySummary,512),warnings:array(object({id,code:{type:'string',minLength:1,maxLength:256}}),1024)})),value=>value.recordings.every(recording=>recording.endTick>=recording.startTick));
export const validateReplayOpenResponse=protect(compileNamed<ReplayOpenResponse>('validateReplayOpenResponse',object({replayId,startTick:nonnegativeInteger,endTick:nonnegativeInteger,players:array(publicPlayer,11)})),value=>value.endTick>=value.startTick);
export const validateReplayStepResponse=protect(compileNamed<ReplayStepResponse>('validateReplayStepResponse',object({replayId,startTick:nonnegativeInteger,endTick:nonnegativeInteger,tick:nonnegativeInteger,done:flag,view:viewSchema})),value=>value.tick>=value.startTick&&value.tick<=value.endTick&&value.view.tick===value.tick&&validViewTiming(value.view),1000000);
export const validateLobbyState = protect(compileNamed<LobbyState>('validateLobbyState', lobbySchema));
export const validateSessionResponse = protect(compileNamed<SessionResponse>('validateSessionResponse', sessionSchema));
export const validatePlayerView = protect(compileNamed<PlayerView>('validatePlayerView', viewSchema), validViewTiming, 1000000);
export const validatePlayerViewDelta = protect(compileNamed<PlayerViewDelta>('validatePlayerViewDelta',deltaSchema),validViewTiming,1000000);
export const validateSnapshotChunk = protect(compileNamed<SnapshotChunk>('validateSnapshotChunk',chunkSchema));
export const validateDeltaChunk = protect(compileNamed<DeltaChunk>('validateDeltaChunk',deltaChunkSchema),chunk=>chunk.sequence>chunk.baseSequence);
const boundedNumber=(minimum:number,maximum:number,integer=false)=>({type:integer?'integer':'number',minimum,maximum});
const code={type:'string',minLength:1,maxLength:96};
const plainText=(maxLength:number,minLength=0)=>({type:'string',minLength,maxLength,pattern:'^[^\\u0000-\\u001f\\u007f]*$'});
const endpointMode={enum:['unprobed','schema','json_object','prompt_json']};
const endpointSettings=object({baseUrl:plainText(2048),model:plainText(256),providerProfile:{enum:['generic_openai_compatible','llama_cpp','vllm']},timeoutSeconds:boundedNumber(1,120),maxConcurrent:boundedNumber(1,5,true),inputTokenBudget:boundedNumber(256,32000,true),maxOutputTokens:boundedNumber(64,2048,true),intervalSeconds:object({easy:boundedNumber(10,120),medium:boundedNumber(10,120),hard:boundedNumber(10,120)}),maxAdaptiveIntervalSeconds:boundedNumber(30,120),temperature:boundedNumber(0,2),sendHumanChat:flag,providerOptions:object({top_p:progress,top_k:boundedNumber(1,100,true),min_p:progress,repeat_penalty:boundedNumber(0,2),repetition_penalty:boundedNumber(0,2),presence_penalty:boundedNumber(-2,2),frequency_penalty:boundedNumber(-2,2),seed:boundedNumber(0,4294967295,true),chat_template_kwargs:object({enable_thinking:flag}),reasoning_effort:{enum:['none','low','medium','high']}},[])});
export const validateEndpointSettings=protect(compileNamed<EndpointSettings>('validateEndpointSettings',endpointSettings));
export const validateEndpointUpdateRequest=protect(compileNamed<EndpointUpdateRequest>('validateEndpointUpdateRequest',object({settings:endpointSettings,apiKey:{anyOf:[plainText(4096,1),{type:'null'}]}},['settings'])));
export const validateEndpointStateResponse=protect(compileNamed<EndpointStateResponse>('validateEndpointStateResponse',object({settings:endpointSettings,hasApiKey:flag,configured:flag,capability:object({mode:endpointMode,status:code,checkedAt:nonnegativeInteger},['mode','status'])})));
export const validateEndpointProbeResponse=protect(compileNamed<EndpointProbeResponse>('validateEndpointProbeResponse',object({success:flag,status:code,mode:endpointMode,schemaStatus:code,modelsStatus:code,roundTripMs:nonnegativeNumber})));
const modelLabel={type:'string',minLength:1,maxLength:64,pattern:'^[^\\u0000-\\u001f\\u007f]+$'};
const assistantPreferences={...object({modelId:{anyOf:[id,{type:'null'}]},enabled:flag,reserve:object({food:boundedNumber(0,1000000,true),wood:boundedNumber(0,1000000,true),gold:boundedNumber(0,1000000,true),stone:boundedNumber(0,1000000,true)})}),if:{properties:{enabled:{const:true}},required:['enabled']},then:{properties:{modelId:id}}};
const assistantState=object({preferences:assistantPreferences,status:{enum:['manual','model','fallback','paused','unavailable']},protectedEntityIds:{...array(id,16000),uniqueItems:true}});
export const validateAiModelCatalogResponse=protect(compileNamed<AiModelCatalogResponse>('validateAiModelCatalogResponse',object({models:array(object({id,label:modelLabel,enabled:flag,settings:endpointSettings,hasApiKey:flag,configured:flag,capability:object({mode:endpointMode,status:code,checkedAt:nonnegativeInteger},['mode','status'])}),16)})));
export const validateAiModelUpsertRequest=protect(compileNamed<AiModelUpsertRequest>('validateAiModelUpsertRequest',object({id,label:modelLabel,enabled:flag,settings:endpointSettings,apiKey:{anyOf:[plainText(4096,1),{type:'null'}]}},['label','enabled','settings'])));
export const validateAiModelAssignmentRequest=protect(compileNamed<AiModelAssignmentRequest>('validateAiModelAssignmentRequest',object({playerId:id,modelId:id})));
export const validateAssistantPreferences=protect(compileNamed<AssistantPreferences>('validateAssistantPreferences',assistantPreferences));
export const validateAssistantStateResponse=protect(compileNamed<AssistantStateResponse>('validateAssistantStateResponse',assistantState));
export const validateAssistantOptionsResponse=protect(compileNamed<AssistantOptionsResponse>('validateAssistantOptionsResponse',object({models:array(object({id,label:modelLabel,available:flag}),16),assistant:assistantState})));
export const validateAssistantReleaseRequest=protect(compileNamed<AssistantReleaseRequest>('validateAssistantReleaseRequest',object({entityIds:{...array(id,200),minItems:1,uniqueItems:true}})));
const percentiles=object({p50:nonnegativeNumber,p95:nonnegativeNumber,p99:nonnegativeNumber,max:nonnegativeNumber},['p50','p95','max']),nullableMetric={anyOf:[nonnegativeNumber,{type:'null'}]},nullableCount={anyOf:[nonnegativeInteger,{type:'null'}]};
const loadStatistics=object({unitsTrained:nonnegativeInteger,unitsLost:nonnegativeInteger,buildingsBuilt:nonnegativeInteger,buildingsLost:nonnegativeInteger,ageTicks:object({'1':nonnegativeInteger,'2':nonnegativeInteger,'3':nonnegativeInteger,'4':nonnegativeInteger,'5':nonnegativeInteger,'6':nonnegativeInteger,'7':nonnegativeInteger,'8':nonnegativeInteger},[]),fallbackTicks:nonnegativeInteger,modelReadyTicks:nonnegativeInteger,inferenceFailures:nonnegativeInteger});
const activityActionTicks=object(Object.fromEntries(['move','attack','gather_food','gather_wood','mine','build','repair','carry'].map(kind=>[kind,nonnegativeInteger])),[]);
const activityWindow=object({matchId:id,matchEpoch:nonnegativeInteger,fromTick:nonnegativeInteger,toTick:nonnegativeInteger,actionTicks:activityActionTicks,factions:array(object({playerId:id,uniqueActiveUnits:nonnegativeInteger,activeSurvivingUnits:nonnegativeInteger,survivingUnits:nonnegativeInteger,actionTicks:activityActionTicks,depositedMilli:resources}),11)});
const computeWorkerLane=object({mode:{enum:['threads','inline']},threadIds:{...array(boundedNumber(1,2147483647,true),9),uniqueItems:true},pending:boundedNumber(0,4096,true),recoveries:nonnegativeInteger,degraded:flag});
const workerCallbackSummary=object({operation:code,tick:nullableCount,endTick:nullableCount,epoch:nullableCount,durationMs:nonnegativeNumber,gapBeforeMs:nullableMetric,
  phasesMs:object({commandDrain:nonnegativeNumber,coreStep:nonnegativeNumber,activityProjection:nonnegativeNumber,viewAssemblyPost:nonnegativeNumber,journalCheckpoint:nonnegativeNumber,other:nonnegativeNumber})});
const workerRuntimeSummary=object({historyLimit:{const:16},callbackCount:nonnegativeInteger,boundaryYields:nonnegativeInteger,recentCallbacks:array(workerCallbackSummary,16),
  lastOverload:{anyOf:[{type:'null'},object({tick:nonnegativeInteger,epoch:nonnegativeInteger,debtMs:nonnegativeNumber,boundaryQueued:boundedNumber(0,4096,true),pendingCommands:nonnegativeInteger,
    precedingCallbacks:array(workerCallbackSummary,16),precedingAdvancingCallbacks:array(workerCallbackSummary,16)})]}});
const aiRenewalDiagnostics=object({estimateSource:{const:'joint_queue_to_acceptance'},samples:boundedNumber(0,4096,true),warmup:flag,
  commanders:array(object({playerId:id,leadMs:nullableMetric,remainingPlanTicks:nullableCount,estimatedDeadlineFeasible:{anyOf:[flag,{type:'null'}]},nextDueInMs:nonnegativeNumber}),11)});
const movementTier={enum:[0,1,2,3]};
const simulationPacing=object({movementTier,movementDecisionIntervalMs:{enum:[50,100,150,200,300,450,600]},publicationIntervalMs:{enum:[100,150,200,300,450,600]},committedTimeMs:nonnegativeInteger,frameRevision:nonnegativeInteger,authoritativeIntervalMs:{enum:[50,300,450,600]},tierChanges:nonnegativeInteger,lastTierChange:{anyOf:[{type:'null'},object({tick:nonnegativeInteger,fromTier:movementTier,toTier:movementTier,reason:{enum:['sustained_overload','headroom','recovery_failed']}})]},policy:{enum:['adaptive','pause']},speedPercent:boundedNumber(10,100,true),tickIntervalMs:boundedNumber(50,6000),reductions:nonnegativeInteger,recoveries:nonnegativeInteger,memoryRecoveryBlocked:flag,lastRecovery:{anyOf:[{type:'null'},object({tick:nonnegativeInteger,fromPercent:boundedNumber(10,100,true),toPercent:boundedNumber(10,100,true)})]},selfPaced:flag,deferredWallMs:nonnegativeNumber,lastReduction:{anyOf:[{type:'null'},object({tick:nonnegativeInteger,fromPercent:boundedNumber(10,100,true),toPercent:boundedNumber(10,100,true),debtMs:nonnegativeNumber})]}},['policy','speedPercent','tickIntervalMs','reductions','selfPaced','deferredWallMs','lastReduction']),simulationPacingInterval={...simulationPacing,allOf:[...[300,450,600].map(interval=>({if:{properties:{authoritativeIntervalMs:{const:interval}},required:['authoritativeIntervalMs']},then:{properties:{tickIntervalMs:boundedNumber(interval,interval*10)}}})),{if:{not:{properties:{authoritativeIntervalMs:{enum:[300,450,600]}},required:['authoritativeIntervalMs']}},then:{properties:{tickIntervalMs:boundedNumber(50,500)}}}]};
const localPlanning=object({mode:{const:'deferred-v1'},waitingForCredit:boundedNumber(0,2200,true),queued:boundedNumber(0,2200,true),inflight:boundedNumber(0,2200,true),ready:boundedNumber(0,2200,true),retry:boundedNumber(0,2200,true),oldestWaitMs:nonnegativeInteger,prepared:nonnegativeInteger,admitted:nonnegativeInteger,used:nonnegativeInteger,discarded:nonnegativeInteger});
const simulationFrame=object({frameRevision:nonnegativeInteger,committedTimeMs:nonnegativeInteger,authoritativeIntervalMs:{enum:[50,300,450,600]},phases:object(Object.fromEntries(SIMULATION_FRAME_PHASES.map(phase=>[phase,nonnegativeNumber])),[]),localPlanning},['frameRevision','committedTimeMs','authoritativeIntervalMs','phases']);
const simulationDiagnostics=object({cycleMs:percentiles,cycleSamples:boundedNumber(0,1200,true),callbackMs:percentiles,callbackSamples:boundedNumber(0,1200,true),frame:simulationFrame,pacing:simulationPacingInterval,movementDecisions:object({full:nonnegativeInteger,reused:nonnegativeInteger,attempted:nonnegativeInteger}),runtime:workerRuntimeSummary,compute:object({planning:computeWorkerLane,vision:computeWorkerLane,boundaryQueued:boundedNumber(0,4096,true)}),tick:nonnegativeInteger,tickMs:percentiles,debtMs:nonnegativeNumber,overrunWarning:flag,status:{enum:['SETUP','LOBBY','LOADING','COUNTDOWN','RUNNING','PAUSED','FINISHED','ARCHIVED']},path:{anyOf:[object({work:nonnegativeInteger,pending:nonnegativeInteger,ready:nonnegativeInteger,blocked:nonnegativeInteger,regionCount:nonnegativeInteger,cacheHits:nonnegativeInteger}),{type:'null'}]},world:object({units:nonnegativeInteger,population:nonnegativeInteger,resourceNodes:nonnegativeInteger,activeResourceNodes:nonnegativeInteger,nonnegativeResources:flag,factions:array(object({playerId:id,kind:{enum:['human','ai']},age:boundedNumber(1,8,true),defeated:flag,units:nonnegativeInteger,population:nonnegativeInteger,nonWallBuildings:nonnegativeInteger,wallEquivalentCells:nonnegativeInteger,statistics:loadStatistics,collected:resources}),11)},['units','population','resourceNodes','nonnegativeResources','factions']),activity:object({movingSinceLastSample:nonnegativeInteger,gathering:nonnegativeInteger,returning:nonnegativeInteger,building:nonnegativeInteger,repairing:nonnegativeInteger,blocked:nonnegativeInteger,attackCooldownActive:nonnegativeInteger,sampledTicks:nonnegativeInteger}),activityWindow,memory:object({rss:nonnegativeInteger,heapTotal:nonnegativeInteger,heapUsed:nonnegativeInteger,external:nonnegativeInteger,arrayBuffers:nonnegativeInteger})},['tick','tickMs','debtMs','overrunWarning']);
const aiRequestStage={enum:['preparation','endpoint','application']};
const aiRequestStages=object(Object.fromEntries(['preparation','endpoint','application'].map(stage=>[stage,object({samples:boundedNumber(0,4096,true),durationMs:percentiles,failures:nonnegativeInteger,timeouts:nonnegativeInteger})])));
export const validateEndpointDiagnosticsResponse=protect(compileNamed<EndpointDiagnosticsResponse>('validateEndpointDiagnosticsResponse',object({
  endpoint:object({configured:flag,mode:endpointMode,status:code}),
  scheduler:object({stages:aiRequestStages,recentFailures:array(object({playerId:id,code:{...code,pattern:'^[A-Z][A-Z0-9_]*$'},at:nonnegativeInteger,stage:aiRequestStage},['playerId','code','at']),16),renewal:aiRenewalDiagnostics,active:boundedNumber(0,11,true),pending:boundedNumber(0,11,true),concurrency:boundedNumber(1,11,true),circuit:{enum:['closed','open','half_open']},retryAfterMs:nonnegativeNumber,consecutiveFailures:nonnegativeInteger,completed:nonnegativeInteger,failed:nonnegativeInteger,latencyMs:percentiles,queueDelayMs:percentiles,promptTokens:nullableCount,completionTokens:nullableCount,prefillMs:nullableMetric,generationMs:nullableMetric,usageTotals:object({reportedRequests:nonnegativeInteger,missingUsageRequests:nonnegativeInteger,promptTokens:nonnegativeInteger,completionTokens:nonnegativeInteger,totalTokens:nonnegativeInteger}),commanders:array(object({playerId:id,mode:{enum:['model','fallback']},inFlight:flag,pending:flag,intervalSeconds:nonnegativeNumber,lastStatus:code,lastLatencyMs:nullableMetric,lastAcceptedAt:nullableMetric,requests:object({completed:nonnegativeInteger,failed:nonnegativeInteger,queueSamples:boundedNumber(0,256,true),queueDelayMs:percentiles,stages:aiRequestStages})},['playerId','mode','inFlight','pending','intervalSeconds','lastStatus','lastLatencyMs']),11)},['active','pending','concurrency','circuit','retryAfterMs','consecutiveFailures','completed','failed','latencyMs','queueDelayMs','promptTokens','completionTokens','prefillMs','generationMs','commanders']),
  simulation:{anyOf:[simulationDiagnostics,{type:'null'}]},compute:object({publication:computeWorkerLane}),publicationDelivery:object({scope:{const:'gateway_publication_socket_callbacks'},channels:array(object({channelId:nonnegativeInteger,playerId:{anyOf:[id,{type:'null'}]},offeredViews:nonnegativeInteger,completedViews:nonnegativeInteger,offeredSequence:nullableCount,completedSequence:nullableCount,offerAgeMs:nullableMetric,lastWriteAgeMs:nullableMetric,completedAgeMs:nullableMetric,maxOfferIntervalMs:nullableMetric,maxCompletedIntervalMs:nullableMetric,pendingSocketWrites:boundedNumber(0,4,true),oldestSocketWriteMs:nullableMetric,lastSocketCallbackMs:nullableMetric,maxSocketCallbackMs:nullableMetric,bufferedBytes:nonnegativeInteger,lastLongGap:{anyOf:[{type:'null'},object({at:nonnegativeNumber,stage:{enum:['offer','completion','socket_callback']},durationMs:nonnegativeNumber})]}}),128)}),process:object({rssMiB:nonnegativeNumber,eventLoopDelayMs:percentiles},['rssMiB']),transport:object({scope:{const:'websocket_application_payload_enqueued'},windowMs:{const:10000},clients:array(object({playerId:{anyOf:[id,{type:'null'}]},connections:boundedNumber(1,Number.MAX_SAFE_INTEGER,true),totalBytes:nonnegativeInteger,bytesPerSecond:nonnegativeNumber}),7)})
},['endpoint','scheduler','simulation','process'])));
const channel={enum:['all','team']},pingCategory={enum:['attack','defend','resource','help']},coordinates={xMm:boundedNumber(0,640000,true),zMm:boundedNumber(0,640000,true)};
const chatMessage=object({id,tick:nonnegativeInteger,senderId:id,channel,text:plainText(500,1),source:{enum:['human','model','system']},requestId:id,targetAiId:id,status:{enum:['requested','planned','completed','declined','blocked','expired']}},['id','tick','senderId','channel','text','source']);
const teamPing=object({id,tick:nonnegativeInteger,senderId:id,...coordinates,category:pingCategory,expiresTick:nonnegativeInteger});
const chatState=object({messages:array(chatMessage,200),pings:array(teamPing,64),sendHumanChat:flag});
export const validateChatStateResponse=protect(compileNamed<ChatStateResponse>('validateChatStateResponse',chatState),value=>new Set(value.messages.map(item=>item.id)).size===value.messages.length&&new Set(value.pings.map(item=>item.id)).size===value.pings.length&&value.pings.every(ping=>ping.expiresTick>=ping.tick));
export const validateChatRequest=protect(compileNamed<ChatRequest>('validateChatRequest',object({text:{...plainText(500,1),allOf:[{pattern:'\\S'}]},channel,targetAiId:id},['text','channel'])));
export const validatePingRequest=protect(compileNamed<PingRequest>('validatePingRequest',object({...coordinates,category:pingCategory})));
export const validateCooperationRequest=protect(compileNamed<CooperationRequest>('validateCooperationRequest',{oneOf:[object({targetAiId:id,action:{const:'defend_base'}}),object({targetAiId:id,action:{const:'attack_ping'},pingId:id}),object({targetAiId:id,action:{const:'tribute'},resource,amount:boundedNumber(1,1000,true)})]}));
export const validateServerSocketMessage = protect(compileNamed<ServerSocketMessage>('validateServerSocketMessage', {oneOf:[object({type:{const:'snapshot'},view:viewSchema}),object({type:{const:'delta'},delta:deltaSchema}),chunkSchema,deltaChunkSchema,object({type:{const:'lobby'},lobby:lobbySchema}),object({type:{const:'receipt'},receipt}),object({type:{const:'command_received'},commandId:id,sequence:nonnegativeInteger}),object({type:{const:'error'},code:{type:'string',minLength:1,maxLength:96}}),object({type:{const:'communication'},state:chatState})]}),message=>message.type==='snapshot'?validViewTiming(message.view):message.type==='delta'?validViewTiming(message.delta):message.type==='delta_chunk'?message.sequence>message.baseSequence:message.type!=='communication'||validateChatStateResponse(message.state),1000000);

export const standaloneReferences: Record<string,string> = {"validateClientCommand":"urn:frontier:compiled:validateClientCommand","validateAiPlan":"urn:frontier:compiled:validateAiPlan","validateJoin":"urn:frontier:compiled:validateJoin","validateReady":"urn:frontier:compiled:validateReady","validateBootstrap":"urn:frontier:compiled:validateBootstrap","validateLoaded":"urn:frontier:compiled:validateLoaded","validateLobbyConfig":"urn:frontier:compiled:validateLobbyConfig","validateClientSocketMessage":"urn:frontier:compiled:validateClientSocketMessage","validateLobbyState":"urn:frontier:compiled:validateLobbyState","validateSessionResponse":"urn:frontier:compiled:validateSessionResponse","validatePlayerView":"urn:frontier:compiled:validatePlayerView","validateServerSocketMessage":"urn:frontier:compiled:validateServerSocketMessage"};
for(const name of ['validateEndpointSettings','validateEndpointUpdateRequest','validateEndpointStateResponse','validateEndpointProbeResponse','validateEndpointDiagnosticsResponse','validateChatStateResponse','validateChatRequest','validatePingRequest','validateCooperationRequest'])standaloneReferences[name]='urn:frontier:compiled:'+name;

function compileNamed<T>(name:string,schema:object):ValidateFunction<T> { const existingId=(schema as { $id?:string }).$id; if(existingId) { const result=ajv.compile<T>(schema); ajv.addSchema({$id:'urn:frontier:compiled:'+name,$ref:existingId}); return result; } return ajv.compile<T>({...schema,$id:'urn:frontier:compiled:'+name}); }
standaloneReferences.validateEmptyRequest = 'urn:frontier:compiled:validateEmptyRequest';
standaloneReferences.validatePauseRequest = 'urn:frontier:compiled:validatePauseRequest';
standaloneReferences.validateTeamAssignmentRequest = 'urn:frontier:compiled:validateTeamAssignmentRequest';
standaloneReferences.validatePlayerViewDelta='urn:frontier:compiled:validatePlayerViewDelta';
standaloneReferences.validateSnapshotChunk='urn:frontier:compiled:validateSnapshotChunk';
standaloneReferences.validateDeltaChunk='urn:frontier:compiled:validateDeltaChunk';
standaloneReferences.validateHostRecoveryResponse='urn:frontier:compiled:validateHostRecoveryResponse';
standaloneReferences.validateRejoinInviteResponse='urn:frontier:compiled:validateRejoinInviteResponse';
standaloneReferences.validateReplayListResponse='urn:frontier:compiled:validateReplayListResponse';
standaloneReferences.validateReplayOpenResponse='urn:frontier:compiled:validateReplayOpenResponse';
standaloneReferences.validateReplayStepResponse='urn:frontier:compiled:validateReplayStepResponse';
for(const name of ['validateAiModelCatalogResponse','validateAiModelUpsertRequest','validateAiModelAssignmentRequest','validateAssistantPreferences','validateAssistantStateResponse','validateAssistantOptionsResponse','validateAssistantReleaseRequest'])standaloneReferences[name]='urn:frontier:compiled:'+name;
